apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "volatile-labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: show-text
      {{- include "stable-labels" . | indent 6 }}
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        revision: {{ .Release.Revision | quote }}
      labels:
        app: show-text
        {{- include "stable-labels" . | indent 8 }}
    spec:
      containers:
        - name: runner
          image: {{ .Values.imageName }}:{{ .Values.imageTag }}
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}
                  key: mongodb_uri
                  optional: false
          ports:
            - name: http-port
              containerPort: {{ .Values.port }}
      restartPolicy: Always
