apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "stable-labels" . | indent 4 }}
type: Opaque
data:
  mongodb_uri: {{ .Values.mongoDBURI | b64enc }}
