apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "stable-labels" . | indent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.port }}
      name: http-port
  selector:
    app: show-text
    {{- include "stable-labels" . | indent 4 }}
